// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MistreatedRecord mistreated record
//
// swagger:model mistreatedRecord
type MistreatedRecord struct {

	// artist
	Artist string `json:"artist,omitempty"`

	// last played
	// Format: date-time
	LastPlayed strfmt.DateTime `json:"lastPlayed,omitempty"`

	// neglect score
	NeglectScore float32 `json:"neglectScore,omitempty"`

	// side label
	SideLabel string `json:"sideLabel,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this mistreated record
func (m *MistreatedRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastPlayed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MistreatedRecord) validateLastPlayed(formats strfmt.Registry) error {
	if swag.IsZero(m.LastPlayed) { // not required
		return nil
	}

	if err := validate.FormatOf("lastPlayed", "body", "date-time", m.LastPlayed.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this mistreated record based on context it is used
func (m *MistreatedRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MistreatedRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MistreatedRecord) UnmarshalBinary(b []byte) error {
	var res MistreatedRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
