// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlayPayload play payload
//
// swagger:model playPayload
type PlayPayload struct {

	// artist
	// Required: true
	Artist *string `json:"artist"`

	// title
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this play payload
func (m *PlayPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArtist(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlayPayload) validateArtist(formats strfmt.Registry) error {

	if err := validate.Required("artist", "body", m.Artist); err != nil {
		return err
	}

	return nil
}

func (m *PlayPayload) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this play payload based on context it is used
func (m *PlayPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayPayload) UnmarshalBinary(b []byte) error {
	var res PlayPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
