// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UserScope user scope
//
// swagger:model userScope
type UserScope string

func NewUserScope(value UserScope) *UserScope {
	return &value
}

// Pointer returns a pointer to a freshly-allocated UserScope.
func (m UserScope) Pointer() *UserScope {
	return &m
}

const (

	// UserScopeApp captures enum value "app"
	UserScopeApp UserScope = "app"

	// UserScopeCms captures enum value "cms"
	UserScopeCms UserScope = "cms"
)

// for schema
var userScopeEnum []interface{}

func init() {
	var res []UserScope
	if err := json.Unmarshal([]byte(`["app","cms"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userScopeEnum = append(userScopeEnum, v)
	}
}

func (m UserScope) validateUserScopeEnum(path, location string, value UserScope) error {
	if err := validate.EnumCase(path, location, value, userScopeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this user scope
func (m UserScope) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateUserScopeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this user scope based on context it is used
func (m UserScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
