// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VinylPayload vinyl payload
//
// swagger:model vinylPayload
type VinylPayload struct {

	// discogs Id
	// Required: true
	DiscogsID *int64 `json:"discogsId"`
}

// Validate validates this vinyl payload
func (m *VinylPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiscogsID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VinylPayload) validateDiscogsID(formats strfmt.Registry) error {

	if err := validate.Required("discogsId", "body", m.DiscogsID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this vinyl payload based on context it is used
func (m *VinylPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VinylPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VinylPayload) UnmarshalBinary(b []byte) error {
	var res VinylPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
