// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VinylRecord vinyl record
//
// swagger:model vinylRecord
type VinylRecord struct {

	// artist
	// Required: true
	Artist *string `json:"artist"`

	// cover image
	CoverImage string `json:"coverImage,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// discogs Id
	// Required: true
	DiscogsID *int64 `json:"discogsId"`

	// genres
	Genres []string `json:"genres"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// styles
	Styles []string `json:"styles"`

	// thumb image
	ThumbImage string `json:"thumbImage,omitempty"`

	// title
	// Required: true
	Title *string `json:"title"`

	// year
	Year int64 `json:"year,omitempty"`
}

// Validate validates this vinyl record
func (m *VinylRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArtist(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiscogsID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VinylRecord) validateArtist(formats strfmt.Registry) error {

	if err := validate.Required("artist", "body", m.Artist); err != nil {
		return err
	}

	return nil
}

func (m *VinylRecord) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("createdAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *VinylRecord) validateDiscogsID(formats strfmt.Registry) error {

	if err := validate.Required("discogsId", "body", m.DiscogsID); err != nil {
		return err
	}

	return nil
}

func (m *VinylRecord) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *VinylRecord) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this vinyl record based on context it is used
func (m *VinylRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VinylRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VinylRecord) UnmarshalBinary(b []byte) error {
	var res VinylRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
