// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VinylRecord is an object representing the database table.
type VinylRecord struct {
	ID         int               `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title      string            `boil:"title" json:"title" toml:"title" yaml:"title"`
	Artist     string            `boil:"artist" json:"artist" toml:"artist" yaml:"artist"`
	DiscogsID  int               `boil:"discogs_id" json:"discogs_id" toml:"discogs_id" yaml:"discogs_id"`
	CreatedAt  time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time         `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	Year       null.Int          `boil:"year" json:"year,omitempty" toml:"year" yaml:"year,omitempty"`
	CoverImage null.String       `boil:"cover_image" json:"cover_image,omitempty" toml:"cover_image" yaml:"cover_image,omitempty"`
	ThumbImage null.String       `boil:"thumb_image" json:"thumb_image,omitempty" toml:"thumb_image" yaml:"thumb_image,omitempty"`
	Genres     types.StringArray `boil:"genres" json:"genres,omitempty" toml:"genres" yaml:"genres,omitempty"`
	Styles     types.StringArray `boil:"styles" json:"styles,omitempty" toml:"styles" yaml:"styles,omitempty"`

	R *vinylRecordR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vinylRecordL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VinylRecordColumns = struct {
	ID         string
	Title      string
	Artist     string
	DiscogsID  string
	CreatedAt  string
	UpdatedAt  string
	Year       string
	CoverImage string
	ThumbImage string
	Genres     string
	Styles     string
}{
	ID:         "id",
	Title:      "title",
	Artist:     "artist",
	DiscogsID:  "discogs_id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	Year:       "year",
	CoverImage: "cover_image",
	ThumbImage: "thumb_image",
	Genres:     "genres",
	Styles:     "styles",
}

var VinylRecordTableColumns = struct {
	ID         string
	Title      string
	Artist     string
	DiscogsID  string
	CreatedAt  string
	UpdatedAt  string
	Year       string
	CoverImage string
	ThumbImage string
	Genres     string
	Styles     string
}{
	ID:         "vinyl_records.id",
	Title:      "vinyl_records.title",
	Artist:     "vinyl_records.artist",
	DiscogsID:  "vinyl_records.discogs_id",
	CreatedAt:  "vinyl_records.created_at",
	UpdatedAt:  "vinyl_records.updated_at",
	Year:       "vinyl_records.year",
	CoverImage: "vinyl_records.cover_image",
	ThumbImage: "vinyl_records.thumb_image",
	Genres:     "vinyl_records.genres",
	Styles:     "vinyl_records.styles",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

func (w whereHelpertypes_StringArray) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_StringArray) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var VinylRecordWhere = struct {
	ID         whereHelperint
	Title      whereHelperstring
	Artist     whereHelperstring
	DiscogsID  whereHelperint
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
	Year       whereHelpernull_Int
	CoverImage whereHelpernull_String
	ThumbImage whereHelpernull_String
	Genres     whereHelpertypes_StringArray
	Styles     whereHelpertypes_StringArray
}{
	ID:         whereHelperint{field: "\"vinyl_records\".\"id\""},
	Title:      whereHelperstring{field: "\"vinyl_records\".\"title\""},
	Artist:     whereHelperstring{field: "\"vinyl_records\".\"artist\""},
	DiscogsID:  whereHelperint{field: "\"vinyl_records\".\"discogs_id\""},
	CreatedAt:  whereHelpertime_Time{field: "\"vinyl_records\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"vinyl_records\".\"updated_at\""},
	Year:       whereHelpernull_Int{field: "\"vinyl_records\".\"year\""},
	CoverImage: whereHelpernull_String{field: "\"vinyl_records\".\"cover_image\""},
	ThumbImage: whereHelpernull_String{field: "\"vinyl_records\".\"thumb_image\""},
	Genres:     whereHelpertypes_StringArray{field: "\"vinyl_records\".\"genres\""},
	Styles:     whereHelpertypes_StringArray{field: "\"vinyl_records\".\"styles\""},
}

// VinylRecordRels is where relationship names are stored.
var VinylRecordRels = struct {
	VinylSides string
}{
	VinylSides: "VinylSides",
}

// vinylRecordR is where relationships are stored.
type vinylRecordR struct {
	VinylSides VinylSideSlice `boil:"VinylSides" json:"VinylSides" toml:"VinylSides" yaml:"VinylSides"`
}

// NewStruct creates a new relationship struct
func (*vinylRecordR) NewStruct() *vinylRecordR {
	return &vinylRecordR{}
}

func (o *VinylRecord) GetVinylSides() VinylSideSlice {
	if o == nil {
		return nil
	}

	return o.R.GetVinylSides()
}

func (r *vinylRecordR) GetVinylSides() VinylSideSlice {
	if r == nil {
		return nil
	}

	return r.VinylSides
}

// vinylRecordL is where Load methods for each relationship are stored.
type vinylRecordL struct{}

var (
	vinylRecordAllColumns            = []string{"id", "title", "artist", "discogs_id", "created_at", "updated_at", "year", "cover_image", "thumb_image", "genres", "styles"}
	vinylRecordColumnsWithoutDefault = []string{"title", "artist", "discogs_id"}
	vinylRecordColumnsWithDefault    = []string{"id", "created_at", "updated_at", "year", "cover_image", "thumb_image", "genres", "styles"}
	vinylRecordPrimaryKeyColumns     = []string{"id"}
	vinylRecordGeneratedColumns      = []string{}
)

type (
	// VinylRecordSlice is an alias for a slice of pointers to VinylRecord.
	// This should almost always be used instead of []VinylRecord.
	VinylRecordSlice []*VinylRecord

	vinylRecordQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vinylRecordType                 = reflect.TypeOf(&VinylRecord{})
	vinylRecordMapping              = queries.MakeStructMapping(vinylRecordType)
	vinylRecordPrimaryKeyMapping, _ = queries.BindMapping(vinylRecordType, vinylRecordMapping, vinylRecordPrimaryKeyColumns)
	vinylRecordInsertCacheMut       sync.RWMutex
	vinylRecordInsertCache          = make(map[string]insertCache)
	vinylRecordUpdateCacheMut       sync.RWMutex
	vinylRecordUpdateCache          = make(map[string]updateCache)
	vinylRecordUpsertCacheMut       sync.RWMutex
	vinylRecordUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single vinylRecord record from the query.
func (q vinylRecordQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VinylRecord, error) {
	o := &VinylRecord{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vinyl_records")
	}

	return o, nil
}

// All returns all VinylRecord records from the query.
func (q vinylRecordQuery) All(ctx context.Context, exec boil.ContextExecutor) (VinylRecordSlice, error) {
	var o []*VinylRecord

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VinylRecord slice")
	}

	return o, nil
}

// Count returns the count of all VinylRecord records in the query.
func (q vinylRecordQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vinyl_records rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vinylRecordQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vinyl_records exists")
	}

	return count > 0, nil
}

// VinylSides retrieves all the vinyl_side's VinylSides with an executor.
func (o *VinylRecord) VinylSides(mods ...qm.QueryMod) vinylSideQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"vinyl_sides\".\"vinyl_record_id\"=?", o.ID),
	)

	return VinylSides(queryMods...)
}

// LoadVinylSides allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (vinylRecordL) LoadVinylSides(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVinylRecord interface{}, mods queries.Applicator) error {
	var slice []*VinylRecord
	var object *VinylRecord

	if singular {
		var ok bool
		object, ok = maybeVinylRecord.(*VinylRecord)
		if !ok {
			object = new(VinylRecord)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVinylRecord)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVinylRecord))
			}
		}
	} else {
		s, ok := maybeVinylRecord.(*[]*VinylRecord)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVinylRecord)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVinylRecord))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &vinylRecordR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vinylRecordR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`vinyl_sides`),
		qm.WhereIn(`vinyl_sides.vinyl_record_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load vinyl_sides")
	}

	var resultSlice []*VinylSide
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice vinyl_sides")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on vinyl_sides")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for vinyl_sides")
	}

	if singular {
		object.R.VinylSides = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &vinylSideR{}
			}
			foreign.R.VinylRecord = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.VinylRecordID {
				local.R.VinylSides = append(local.R.VinylSides, foreign)
				if foreign.R == nil {
					foreign.R = &vinylSideR{}
				}
				foreign.R.VinylRecord = local
				break
			}
		}
	}

	return nil
}

// AddVinylSides adds the given related objects to the existing relationships
// of the vinyl_record, optionally inserting them as new records.
// Appends related to o.R.VinylSides.
// Sets related.R.VinylRecord appropriately.
func (o *VinylRecord) AddVinylSides(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*VinylSide) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.VinylRecordID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"vinyl_sides\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"vinyl_record_id"}),
				strmangle.WhereClause("\"", "\"", 2, vinylSidePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.VinylRecordID = o.ID
		}
	}

	if o.R == nil {
		o.R = &vinylRecordR{
			VinylSides: related,
		}
	} else {
		o.R.VinylSides = append(o.R.VinylSides, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &vinylSideR{
				VinylRecord: o,
			}
		} else {
			rel.R.VinylRecord = o
		}
	}
	return nil
}

// VinylRecords retrieves all the records using an executor.
func VinylRecords(mods ...qm.QueryMod) vinylRecordQuery {
	mods = append(mods, qm.From("\"vinyl_records\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vinyl_records\".*"})
	}

	return vinylRecordQuery{q}
}

// FindVinylRecord retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVinylRecord(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*VinylRecord, error) {
	vinylRecordObj := &VinylRecord{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vinyl_records\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, vinylRecordObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vinyl_records")
	}

	return vinylRecordObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VinylRecord) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vinyl_records provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(vinylRecordColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vinylRecordInsertCacheMut.RLock()
	cache, cached := vinylRecordInsertCache[key]
	vinylRecordInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vinylRecordAllColumns,
			vinylRecordColumnsWithDefault,
			vinylRecordColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vinylRecordType, vinylRecordMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vinylRecordType, vinylRecordMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vinyl_records\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vinyl_records\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vinyl_records")
	}

	if !cached {
		vinylRecordInsertCacheMut.Lock()
		vinylRecordInsertCache[key] = cache
		vinylRecordInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the VinylRecord.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VinylRecord) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	vinylRecordUpdateCacheMut.RLock()
	cache, cached := vinylRecordUpdateCache[key]
	vinylRecordUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vinylRecordAllColumns,
			vinylRecordPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vinyl_records, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vinyl_records\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vinylRecordPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vinylRecordType, vinylRecordMapping, append(wl, vinylRecordPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vinyl_records row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vinyl_records")
	}

	if !cached {
		vinylRecordUpdateCacheMut.Lock()
		vinylRecordUpdateCache[key] = cache
		vinylRecordUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q vinylRecordQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vinyl_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vinyl_records")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VinylRecordSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vinyl_records\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vinylRecordPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vinylRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vinylRecord")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VinylRecord) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vinyl_records provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(vinylRecordColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vinylRecordUpsertCacheMut.RLock()
	cache, cached := vinylRecordUpsertCache[key]
	vinylRecordUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vinylRecordAllColumns,
			vinylRecordColumnsWithDefault,
			vinylRecordColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vinylRecordAllColumns,
			vinylRecordPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vinyl_records, could not build update column list")
		}

		ret := strmangle.SetComplement(vinylRecordAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vinylRecordPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vinyl_records, could not build conflict column list")
			}

			conflict = make([]string, len(vinylRecordPrimaryKeyColumns))
			copy(conflict, vinylRecordPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vinyl_records\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vinylRecordType, vinylRecordMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vinylRecordType, vinylRecordMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vinyl_records")
	}

	if !cached {
		vinylRecordUpsertCacheMut.Lock()
		vinylRecordUpsertCache[key] = cache
		vinylRecordUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single VinylRecord record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VinylRecord) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VinylRecord provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vinylRecordPrimaryKeyMapping)
	sql := "DELETE FROM \"vinyl_records\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vinyl_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vinyl_records")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vinylRecordQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vinylRecordQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vinyl_records")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vinyl_records")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VinylRecordSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vinyl_records\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinylRecordPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vinylRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vinyl_records")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VinylRecord) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVinylRecord(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VinylRecordSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VinylRecordSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vinyl_records\".* FROM \"vinyl_records\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinylRecordPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VinylRecordSlice")
	}

	*o = slice

	return nil
}

// VinylRecordExists checks if the VinylRecord row exists.
func VinylRecordExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vinyl_records\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vinyl_records exists")
	}

	return exists, nil
}

// Exists checks if the VinylRecord row exists.
func (o *VinylRecord) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VinylRecordExists(ctx, exec, o.ID)
}
