// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testVinylSides(t *testing.T) {
	t.Parallel()

	query := VinylSides()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testVinylSidesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylSidesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := VinylSides().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylSidesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VinylSideSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylSidesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := VinylSideExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if VinylSide exists: %s", err)
	}
	if !e {
		t.Errorf("Expected VinylSideExists to return true, but got false.")
	}
}

func testVinylSidesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	vinylSideFound, err := FindVinylSide(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if vinylSideFound == nil {
		t.Error("want a record, got nil")
	}
}

func testVinylSidesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = VinylSides().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testVinylSidesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := VinylSides().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testVinylSidesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	vinylSideOne := &VinylSide{}
	vinylSideTwo := &VinylSide{}
	if err = randomize.Struct(seed, vinylSideOne, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}
	if err = randomize.Struct(seed, vinylSideTwo, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = vinylSideOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = vinylSideTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VinylSides().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testVinylSidesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	vinylSideOne := &VinylSide{}
	vinylSideTwo := &VinylSide{}
	if err = randomize.Struct(seed, vinylSideOne, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}
	if err = randomize.Struct(seed, vinylSideTwo, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = vinylSideOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = vinylSideTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testVinylSidesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVinylSidesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(vinylSidePrimaryKeyColumns, vinylSideColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVinylSideToManyTracks(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VinylSide
	var b, c Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, trackDBTypes, false, trackColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, trackDBTypes, false, trackColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.VinylSideID = a.ID
	c.VinylSideID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Tracks().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.VinylSideID == b.VinylSideID {
			bFound = true
		}
		if v.VinylSideID == c.VinylSideID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := VinylSideSlice{&a}
	if err = a.L.LoadTracks(ctx, tx, false, (*[]*VinylSide)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Tracks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Tracks = nil
	if err = a.L.LoadTracks(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Tracks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testVinylSideToManyAddOpTracks(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VinylSide
	var b, c, d, e Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, vinylSideDBTypes, false, strmangle.SetComplement(vinylSidePrimaryKeyColumns, vinylSideColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Track{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Track{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTracks(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.VinylSideID {
			t.Error("foreign key was wrong value", a.ID, first.VinylSideID)
		}
		if a.ID != second.VinylSideID {
			t.Error("foreign key was wrong value", a.ID, second.VinylSideID)
		}

		if first.R.VinylSide != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.VinylSide != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Tracks[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Tracks[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Tracks().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testVinylSideToOneVinylRecordUsingVinylRecord(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local VinylSide
	var foreign VinylRecord

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, vinylRecordDBTypes, false, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.VinylRecordID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.VinylRecord().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := VinylSideSlice{&local}
	if err = local.L.LoadVinylRecord(ctx, tx, false, (*[]*VinylSide)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.VinylRecord == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.VinylRecord = nil
	if err = local.L.LoadVinylRecord(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.VinylRecord == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testVinylSideToOneSetOpVinylRecordUsingVinylRecord(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VinylSide
	var b, c VinylRecord

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, vinylSideDBTypes, false, strmangle.SetComplement(vinylSidePrimaryKeyColumns, vinylSideColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vinylRecordDBTypes, false, strmangle.SetComplement(vinylRecordPrimaryKeyColumns, vinylRecordColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, vinylRecordDBTypes, false, strmangle.SetComplement(vinylRecordPrimaryKeyColumns, vinylRecordColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*VinylRecord{&b, &c} {
		err = a.SetVinylRecord(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.VinylRecord != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.VinylSides[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.VinylRecordID != x.ID {
			t.Error("foreign key was wrong value", a.VinylRecordID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.VinylRecordID))
		reflect.Indirect(reflect.ValueOf(&a.VinylRecordID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.VinylRecordID != x.ID {
			t.Error("foreign key was wrong value", a.VinylRecordID, x.ID)
		}
	}
}

func testVinylSidesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVinylSidesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VinylSideSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVinylSidesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VinylSides().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	vinylSideDBTypes = map[string]string{`ID`: `integer`, `VinylRecordID`: `integer`, `SideLabel`: `text`, `PlayCount`: `integer`, `LastPlayedAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                = bytes.MinRead
)

func testVinylSidesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(vinylSidePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(vinylSideAllColumns) == len(vinylSidePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSidePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testVinylSidesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(vinylSideAllColumns) == len(vinylSidePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VinylSide{}
	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSideColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, vinylSideDBTypes, true, vinylSidePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(vinylSideAllColumns, vinylSidePrimaryKeyColumns) {
		fields = vinylSideAllColumns
	} else {
		fields = strmangle.SetComplement(
			vinylSideAllColumns,
			vinylSidePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := VinylSideSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testVinylSidesUpsert(t *testing.T) {
	t.Parallel()

	if len(vinylSideAllColumns) == len(vinylSidePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := VinylSide{}
	if err = randomize.Struct(seed, &o, vinylSideDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VinylSide: %s", err)
	}

	count, err := VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, vinylSideDBTypes, false, vinylSidePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylSide struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VinylSide: %s", err)
	}

	count, err = VinylSides().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
