// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testVinylRecords(t *testing.T) {
	t.Parallel()

	query := VinylRecords()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testVinylRecordsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylRecordsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := VinylRecords().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylRecordsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VinylRecordSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVinylRecordsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := VinylRecordExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if VinylRecord exists: %s", err)
	}
	if !e {
		t.Errorf("Expected VinylRecordExists to return true, but got false.")
	}
}

func testVinylRecordsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	vinylRecordFound, err := FindVinylRecord(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if vinylRecordFound == nil {
		t.Error("want a record, got nil")
	}
}

func testVinylRecordsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = VinylRecords().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testVinylRecordsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := VinylRecords().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testVinylRecordsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	vinylRecordOne := &VinylRecord{}
	vinylRecordTwo := &VinylRecord{}
	if err = randomize.Struct(seed, vinylRecordOne, vinylRecordDBTypes, false, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}
	if err = randomize.Struct(seed, vinylRecordTwo, vinylRecordDBTypes, false, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = vinylRecordOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = vinylRecordTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VinylRecords().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testVinylRecordsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	vinylRecordOne := &VinylRecord{}
	vinylRecordTwo := &VinylRecord{}
	if err = randomize.Struct(seed, vinylRecordOne, vinylRecordDBTypes, false, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}
	if err = randomize.Struct(seed, vinylRecordTwo, vinylRecordDBTypes, false, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = vinylRecordOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = vinylRecordTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testVinylRecordsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVinylRecordsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(vinylRecordPrimaryKeyColumns, vinylRecordColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVinylRecordToManyVinylSides(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VinylRecord
	var b, c VinylSide

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, vinylSideDBTypes, false, vinylSideColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.VinylRecordID = a.ID
	c.VinylRecordID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.VinylSides().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.VinylRecordID == b.VinylRecordID {
			bFound = true
		}
		if v.VinylRecordID == c.VinylRecordID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := VinylRecordSlice{&a}
	if err = a.L.LoadVinylSides(ctx, tx, false, (*[]*VinylRecord)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.VinylSides); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.VinylSides = nil
	if err = a.L.LoadVinylSides(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.VinylSides); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testVinylRecordToManyAddOpVinylSides(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a VinylRecord
	var b, c, d, e VinylSide

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, vinylRecordDBTypes, false, strmangle.SetComplement(vinylRecordPrimaryKeyColumns, vinylRecordColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*VinylSide{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, vinylSideDBTypes, false, strmangle.SetComplement(vinylSidePrimaryKeyColumns, vinylSideColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*VinylSide{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddVinylSides(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.VinylRecordID {
			t.Error("foreign key was wrong value", a.ID, first.VinylRecordID)
		}
		if a.ID != second.VinylRecordID {
			t.Error("foreign key was wrong value", a.ID, second.VinylRecordID)
		}

		if first.R.VinylRecord != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.VinylRecord != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.VinylSides[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.VinylSides[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.VinylSides().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testVinylRecordsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVinylRecordsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VinylRecordSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVinylRecordsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VinylRecords().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	vinylRecordDBTypes = map[string]string{`ID`: `integer`, `Title`: `text`, `Artist`: `text`, `DiscogsID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                  = bytes.MinRead
)

func testVinylRecordsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(vinylRecordPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(vinylRecordAllColumns) == len(vinylRecordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testVinylRecordsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(vinylRecordAllColumns) == len(vinylRecordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VinylRecord{}
	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, vinylRecordDBTypes, true, vinylRecordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(vinylRecordAllColumns, vinylRecordPrimaryKeyColumns) {
		fields = vinylRecordAllColumns
	} else {
		fields = strmangle.SetComplement(
			vinylRecordAllColumns,
			vinylRecordPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := VinylRecordSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testVinylRecordsUpsert(t *testing.T) {
	t.Parallel()

	if len(vinylRecordAllColumns) == len(vinylRecordPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := VinylRecord{}
	if err = randomize.Struct(seed, &o, vinylRecordDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VinylRecord: %s", err)
	}

	count, err := VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, vinylRecordDBTypes, false, vinylRecordPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VinylRecord struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VinylRecord: %s", err)
	}

	count, err = VinylRecords().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
