// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRecognizeSongRecognizePostParams creates a new RecognizeSongRecognizePostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRecognizeSongRecognizePostParams() *RecognizeSongRecognizePostParams {
	return &RecognizeSongRecognizePostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRecognizeSongRecognizePostParamsWithTimeout creates a new RecognizeSongRecognizePostParams object
// with the ability to set a timeout on a request.
func NewRecognizeSongRecognizePostParamsWithTimeout(timeout time.Duration) *RecognizeSongRecognizePostParams {
	return &RecognizeSongRecognizePostParams{
		timeout: timeout,
	}
}

// NewRecognizeSongRecognizePostParamsWithContext creates a new RecognizeSongRecognizePostParams object
// with the ability to set a context for a request.
func NewRecognizeSongRecognizePostParamsWithContext(ctx context.Context) *RecognizeSongRecognizePostParams {
	return &RecognizeSongRecognizePostParams{
		Context: ctx,
	}
}

// NewRecognizeSongRecognizePostParamsWithHTTPClient creates a new RecognizeSongRecognizePostParams object
// with the ability to set a custom HTTPClient for a request.
func NewRecognizeSongRecognizePostParamsWithHTTPClient(client *http.Client) *RecognizeSongRecognizePostParams {
	return &RecognizeSongRecognizePostParams{
		HTTPClient: client,
	}
}

/*
RecognizeSongRecognizePostParams contains all the parameters to send to the API endpoint

	for the recognize song recognize post operation.

	Typically these are written to a http.Request.
*/
type RecognizeSongRecognizePostParams struct {

	// File.
	File runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the recognize song recognize post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RecognizeSongRecognizePostParams) WithDefaults() *RecognizeSongRecognizePostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the recognize song recognize post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RecognizeSongRecognizePostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) WithTimeout(timeout time.Duration) *RecognizeSongRecognizePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) WithContext(ctx context.Context) *RecognizeSongRecognizePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) WithHTTPClient(client *http.Client) *RecognizeSongRecognizePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) WithFile(file runtime.NamedReadCloser) *RecognizeSongRecognizePostParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the recognize song recognize post params
func (o *RecognizeSongRecognizePostParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *RecognizeSongRecognizePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
