// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AccessTokens", testAccessTokens)
	t.Run("AppUserProfiles", testAppUserProfiles)
	t.Run("ConfirmationTokens", testConfirmationTokens)
	t.Run("PasswordResetTokens", testPasswordResetTokens)
	t.Run("PushTokens", testPushTokens)
	t.Run("RefreshTokens", testRefreshTokens)
	t.Run("TrackPlays", testTrackPlays)
	t.Run("Tracks", testTracks)
	t.Run("Users", testUsers)
	t.Run("VinylRecords", testVinylRecords)
	t.Run("VinylSides", testVinylSides)
}

func TestDelete(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensDelete)
	t.Run("AppUserProfiles", testAppUserProfilesDelete)
	t.Run("ConfirmationTokens", testConfirmationTokensDelete)
	t.Run("PasswordResetTokens", testPasswordResetTokensDelete)
	t.Run("PushTokens", testPushTokensDelete)
	t.Run("RefreshTokens", testRefreshTokensDelete)
	t.Run("TrackPlays", testTrackPlaysDelete)
	t.Run("Tracks", testTracksDelete)
	t.Run("Users", testUsersDelete)
	t.Run("VinylRecords", testVinylRecordsDelete)
	t.Run("VinylSides", testVinylSidesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensQueryDeleteAll)
	t.Run("AppUserProfiles", testAppUserProfilesQueryDeleteAll)
	t.Run("ConfirmationTokens", testConfirmationTokensQueryDeleteAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensQueryDeleteAll)
	t.Run("PushTokens", testPushTokensQueryDeleteAll)
	t.Run("RefreshTokens", testRefreshTokensQueryDeleteAll)
	t.Run("TrackPlays", testTrackPlaysQueryDeleteAll)
	t.Run("Tracks", testTracksQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
	t.Run("VinylRecords", testVinylRecordsQueryDeleteAll)
	t.Run("VinylSides", testVinylSidesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSliceDeleteAll)
	t.Run("AppUserProfiles", testAppUserProfilesSliceDeleteAll)
	t.Run("ConfirmationTokens", testConfirmationTokensSliceDeleteAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensSliceDeleteAll)
	t.Run("PushTokens", testPushTokensSliceDeleteAll)
	t.Run("RefreshTokens", testRefreshTokensSliceDeleteAll)
	t.Run("TrackPlays", testTrackPlaysSliceDeleteAll)
	t.Run("Tracks", testTracksSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
	t.Run("VinylRecords", testVinylRecordsSliceDeleteAll)
	t.Run("VinylSides", testVinylSidesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensExists)
	t.Run("AppUserProfiles", testAppUserProfilesExists)
	t.Run("ConfirmationTokens", testConfirmationTokensExists)
	t.Run("PasswordResetTokens", testPasswordResetTokensExists)
	t.Run("PushTokens", testPushTokensExists)
	t.Run("RefreshTokens", testRefreshTokensExists)
	t.Run("TrackPlays", testTrackPlaysExists)
	t.Run("Tracks", testTracksExists)
	t.Run("Users", testUsersExists)
	t.Run("VinylRecords", testVinylRecordsExists)
	t.Run("VinylSides", testVinylSidesExists)
}

func TestFind(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensFind)
	t.Run("AppUserProfiles", testAppUserProfilesFind)
	t.Run("ConfirmationTokens", testConfirmationTokensFind)
	t.Run("PasswordResetTokens", testPasswordResetTokensFind)
	t.Run("PushTokens", testPushTokensFind)
	t.Run("RefreshTokens", testRefreshTokensFind)
	t.Run("TrackPlays", testTrackPlaysFind)
	t.Run("Tracks", testTracksFind)
	t.Run("Users", testUsersFind)
	t.Run("VinylRecords", testVinylRecordsFind)
	t.Run("VinylSides", testVinylSidesFind)
}

func TestBind(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensBind)
	t.Run("AppUserProfiles", testAppUserProfilesBind)
	t.Run("ConfirmationTokens", testConfirmationTokensBind)
	t.Run("PasswordResetTokens", testPasswordResetTokensBind)
	t.Run("PushTokens", testPushTokensBind)
	t.Run("RefreshTokens", testRefreshTokensBind)
	t.Run("TrackPlays", testTrackPlaysBind)
	t.Run("Tracks", testTracksBind)
	t.Run("Users", testUsersBind)
	t.Run("VinylRecords", testVinylRecordsBind)
	t.Run("VinylSides", testVinylSidesBind)
}

func TestOne(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensOne)
	t.Run("AppUserProfiles", testAppUserProfilesOne)
	t.Run("ConfirmationTokens", testConfirmationTokensOne)
	t.Run("PasswordResetTokens", testPasswordResetTokensOne)
	t.Run("PushTokens", testPushTokensOne)
	t.Run("RefreshTokens", testRefreshTokensOne)
	t.Run("TrackPlays", testTrackPlaysOne)
	t.Run("Tracks", testTracksOne)
	t.Run("Users", testUsersOne)
	t.Run("VinylRecords", testVinylRecordsOne)
	t.Run("VinylSides", testVinylSidesOne)
}

func TestAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensAll)
	t.Run("AppUserProfiles", testAppUserProfilesAll)
	t.Run("ConfirmationTokens", testConfirmationTokensAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensAll)
	t.Run("PushTokens", testPushTokensAll)
	t.Run("RefreshTokens", testRefreshTokensAll)
	t.Run("TrackPlays", testTrackPlaysAll)
	t.Run("Tracks", testTracksAll)
	t.Run("Users", testUsersAll)
	t.Run("VinylRecords", testVinylRecordsAll)
	t.Run("VinylSides", testVinylSidesAll)
}

func TestCount(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensCount)
	t.Run("AppUserProfiles", testAppUserProfilesCount)
	t.Run("ConfirmationTokens", testConfirmationTokensCount)
	t.Run("PasswordResetTokens", testPasswordResetTokensCount)
	t.Run("PushTokens", testPushTokensCount)
	t.Run("RefreshTokens", testRefreshTokensCount)
	t.Run("TrackPlays", testTrackPlaysCount)
	t.Run("Tracks", testTracksCount)
	t.Run("Users", testUsersCount)
	t.Run("VinylRecords", testVinylRecordsCount)
	t.Run("VinylSides", testVinylSidesCount)
}

func TestInsert(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensInsert)
	t.Run("AccessTokens", testAccessTokensInsertWhitelist)
	t.Run("AppUserProfiles", testAppUserProfilesInsert)
	t.Run("AppUserProfiles", testAppUserProfilesInsertWhitelist)
	t.Run("ConfirmationTokens", testConfirmationTokensInsert)
	t.Run("ConfirmationTokens", testConfirmationTokensInsertWhitelist)
	t.Run("PasswordResetTokens", testPasswordResetTokensInsert)
	t.Run("PasswordResetTokens", testPasswordResetTokensInsertWhitelist)
	t.Run("PushTokens", testPushTokensInsert)
	t.Run("PushTokens", testPushTokensInsertWhitelist)
	t.Run("RefreshTokens", testRefreshTokensInsert)
	t.Run("RefreshTokens", testRefreshTokensInsertWhitelist)
	t.Run("TrackPlays", testTrackPlaysInsert)
	t.Run("TrackPlays", testTrackPlaysInsertWhitelist)
	t.Run("Tracks", testTracksInsert)
	t.Run("Tracks", testTracksInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
	t.Run("VinylRecords", testVinylRecordsInsert)
	t.Run("VinylRecords", testVinylRecordsInsertWhitelist)
	t.Run("VinylSides", testVinylSidesInsert)
	t.Run("VinylSides", testVinylSidesInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensReload)
	t.Run("AppUserProfiles", testAppUserProfilesReload)
	t.Run("ConfirmationTokens", testConfirmationTokensReload)
	t.Run("PasswordResetTokens", testPasswordResetTokensReload)
	t.Run("PushTokens", testPushTokensReload)
	t.Run("RefreshTokens", testRefreshTokensReload)
	t.Run("TrackPlays", testTrackPlaysReload)
	t.Run("Tracks", testTracksReload)
	t.Run("Users", testUsersReload)
	t.Run("VinylRecords", testVinylRecordsReload)
	t.Run("VinylSides", testVinylSidesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensReloadAll)
	t.Run("AppUserProfiles", testAppUserProfilesReloadAll)
	t.Run("ConfirmationTokens", testConfirmationTokensReloadAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensReloadAll)
	t.Run("PushTokens", testPushTokensReloadAll)
	t.Run("RefreshTokens", testRefreshTokensReloadAll)
	t.Run("TrackPlays", testTrackPlaysReloadAll)
	t.Run("Tracks", testTracksReloadAll)
	t.Run("Users", testUsersReloadAll)
	t.Run("VinylRecords", testVinylRecordsReloadAll)
	t.Run("VinylSides", testVinylSidesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSelect)
	t.Run("AppUserProfiles", testAppUserProfilesSelect)
	t.Run("ConfirmationTokens", testConfirmationTokensSelect)
	t.Run("PasswordResetTokens", testPasswordResetTokensSelect)
	t.Run("PushTokens", testPushTokensSelect)
	t.Run("RefreshTokens", testRefreshTokensSelect)
	t.Run("TrackPlays", testTrackPlaysSelect)
	t.Run("Tracks", testTracksSelect)
	t.Run("Users", testUsersSelect)
	t.Run("VinylRecords", testVinylRecordsSelect)
	t.Run("VinylSides", testVinylSidesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensUpdate)
	t.Run("AppUserProfiles", testAppUserProfilesUpdate)
	t.Run("ConfirmationTokens", testConfirmationTokensUpdate)
	t.Run("PasswordResetTokens", testPasswordResetTokensUpdate)
	t.Run("PushTokens", testPushTokensUpdate)
	t.Run("RefreshTokens", testRefreshTokensUpdate)
	t.Run("TrackPlays", testTrackPlaysUpdate)
	t.Run("Tracks", testTracksUpdate)
	t.Run("Users", testUsersUpdate)
	t.Run("VinylRecords", testVinylRecordsUpdate)
	t.Run("VinylSides", testVinylSidesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSliceUpdateAll)
	t.Run("AppUserProfiles", testAppUserProfilesSliceUpdateAll)
	t.Run("ConfirmationTokens", testConfirmationTokensSliceUpdateAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensSliceUpdateAll)
	t.Run("PushTokens", testPushTokensSliceUpdateAll)
	t.Run("RefreshTokens", testRefreshTokensSliceUpdateAll)
	t.Run("TrackPlays", testTrackPlaysSliceUpdateAll)
	t.Run("Tracks", testTracksSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
	t.Run("VinylRecords", testVinylRecordsSliceUpdateAll)
	t.Run("VinylSides", testVinylSidesSliceUpdateAll)
}
