// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTrackPlays(t *testing.T) {
	t.Parallel()

	query := TrackPlays()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTrackPlaysDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackPlaysQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TrackPlays().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackPlaysSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TrackPlaySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackPlaysExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TrackPlayExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TrackPlay exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TrackPlayExists to return true, but got false.")
	}
}

func testTrackPlaysFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	trackPlayFound, err := FindTrackPlay(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if trackPlayFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTrackPlaysBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TrackPlays().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTrackPlaysOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TrackPlays().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTrackPlaysAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	trackPlayOne := &TrackPlay{}
	trackPlayTwo := &TrackPlay{}
	if err = randomize.Struct(seed, trackPlayOne, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}
	if err = randomize.Struct(seed, trackPlayTwo, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = trackPlayOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = trackPlayTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TrackPlays().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTrackPlaysCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	trackPlayOne := &TrackPlay{}
	trackPlayTwo := &TrackPlay{}
	if err = randomize.Struct(seed, trackPlayOne, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}
	if err = randomize.Struct(seed, trackPlayTwo, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = trackPlayOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = trackPlayTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testTrackPlaysInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTrackPlaysInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(trackPlayPrimaryKeyColumns, trackPlayColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTrackPlayToOneTrackUsingTrack(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TrackPlay
	var foreign Track

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, trackDBTypes, false, trackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Track struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TrackID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Track().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := TrackPlaySlice{&local}
	if err = local.L.LoadTrack(ctx, tx, false, (*[]*TrackPlay)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Track = nil
	if err = local.L.LoadTrack(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testTrackPlayToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TrackPlay
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, trackPlayDBTypes, false, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := TrackPlaySlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*TrackPlay)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testTrackPlayToOneSetOpTrackUsingTrack(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TrackPlay
	var b, c Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, trackPlayDBTypes, false, strmangle.SetComplement(trackPlayPrimaryKeyColumns, trackPlayColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Track{&b, &c} {
		err = a.SetTrack(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Track != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TrackPlays[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TrackID != x.ID {
			t.Error("foreign key was wrong value", a.TrackID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TrackID))
		reflect.Indirect(reflect.ValueOf(&a.TrackID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TrackID != x.ID {
			t.Error("foreign key was wrong value", a.TrackID, x.ID)
		}
	}
}
func testTrackPlayToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TrackPlay
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, trackPlayDBTypes, false, strmangle.SetComplement(trackPlayPrimaryKeyColumns, trackPlayColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TrackPlays[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testTrackPlaysReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTrackPlaysReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TrackPlaySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTrackPlaysSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TrackPlays().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	trackPlayDBTypes = map[string]string{`ID`: `integer`, `TrackID`: `integer`, `UserID`: `uuid`, `PlayedAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                = bytes.MinRead
)

func testTrackPlaysUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(trackPlayPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(trackPlayAllColumns) == len(trackPlayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTrackPlaysSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(trackPlayAllColumns) == len(trackPlayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TrackPlay{}
	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, trackPlayDBTypes, true, trackPlayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(trackPlayAllColumns, trackPlayPrimaryKeyColumns) {
		fields = trackPlayAllColumns
	} else {
		fields = strmangle.SetComplement(
			trackPlayAllColumns,
			trackPlayPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TrackPlaySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTrackPlaysUpsert(t *testing.T) {
	t.Parallel()

	if len(trackPlayAllColumns) == len(trackPlayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TrackPlay{}
	if err = randomize.Struct(seed, &o, trackPlayDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TrackPlay: %s", err)
	}

	count, err := TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, trackPlayDBTypes, false, trackPlayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackPlay struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TrackPlay: %s", err)
	}

	count, err = TrackPlays().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
