// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VinylSide is an object representing the database table.
type VinylSide struct {
	ID            int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	VinylRecordID int       `boil:"vinyl_record_id" json:"vinyl_record_id" toml:"vinyl_record_id" yaml:"vinyl_record_id"`
	SideLabel     string    `boil:"side_label" json:"side_label" toml:"side_label" yaml:"side_label"`
	PlayCount     int       `boil:"play_count" json:"play_count" toml:"play_count" yaml:"play_count"`
	LastPlayedAt  null.Time `boil:"last_played_at" json:"last_played_at,omitempty" toml:"last_played_at" yaml:"last_played_at,omitempty"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *vinylSideR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vinylSideL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VinylSideColumns = struct {
	ID            string
	VinylRecordID string
	SideLabel     string
	PlayCount     string
	LastPlayedAt  string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	VinylRecordID: "vinyl_record_id",
	SideLabel:     "side_label",
	PlayCount:     "play_count",
	LastPlayedAt:  "last_played_at",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var VinylSideTableColumns = struct {
	ID            string
	VinylRecordID string
	SideLabel     string
	PlayCount     string
	LastPlayedAt  string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "vinyl_sides.id",
	VinylRecordID: "vinyl_sides.vinyl_record_id",
	SideLabel:     "vinyl_sides.side_label",
	PlayCount:     "vinyl_sides.play_count",
	LastPlayedAt:  "vinyl_sides.last_played_at",
	CreatedAt:     "vinyl_sides.created_at",
	UpdatedAt:     "vinyl_sides.updated_at",
}

// Generated where

var VinylSideWhere = struct {
	ID            whereHelperint
	VinylRecordID whereHelperint
	SideLabel     whereHelperstring
	PlayCount     whereHelperint
	LastPlayedAt  whereHelpernull_Time
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint{field: "\"vinyl_sides\".\"id\""},
	VinylRecordID: whereHelperint{field: "\"vinyl_sides\".\"vinyl_record_id\""},
	SideLabel:     whereHelperstring{field: "\"vinyl_sides\".\"side_label\""},
	PlayCount:     whereHelperint{field: "\"vinyl_sides\".\"play_count\""},
	LastPlayedAt:  whereHelpernull_Time{field: "\"vinyl_sides\".\"last_played_at\""},
	CreatedAt:     whereHelpertime_Time{field: "\"vinyl_sides\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"vinyl_sides\".\"updated_at\""},
}

// VinylSideRels is where relationship names are stored.
var VinylSideRels = struct {
	VinylRecord string
	Tracks      string
}{
	VinylRecord: "VinylRecord",
	Tracks:      "Tracks",
}

// vinylSideR is where relationships are stored.
type vinylSideR struct {
	VinylRecord *VinylRecord `boil:"VinylRecord" json:"VinylRecord" toml:"VinylRecord" yaml:"VinylRecord"`
	Tracks      TrackSlice   `boil:"Tracks" json:"Tracks" toml:"Tracks" yaml:"Tracks"`
}

// NewStruct creates a new relationship struct
func (*vinylSideR) NewStruct() *vinylSideR {
	return &vinylSideR{}
}

func (o *VinylSide) GetVinylRecord() *VinylRecord {
	if o == nil {
		return nil
	}

	return o.R.GetVinylRecord()
}

func (r *vinylSideR) GetVinylRecord() *VinylRecord {
	if r == nil {
		return nil
	}

	return r.VinylRecord
}

func (o *VinylSide) GetTracks() TrackSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTracks()
}

func (r *vinylSideR) GetTracks() TrackSlice {
	if r == nil {
		return nil
	}

	return r.Tracks
}

// vinylSideL is where Load methods for each relationship are stored.
type vinylSideL struct{}

var (
	vinylSideAllColumns            = []string{"id", "vinyl_record_id", "side_label", "play_count", "last_played_at", "created_at", "updated_at"}
	vinylSideColumnsWithoutDefault = []string{"vinyl_record_id", "side_label"}
	vinylSideColumnsWithDefault    = []string{"id", "play_count", "last_played_at", "created_at", "updated_at"}
	vinylSidePrimaryKeyColumns     = []string{"id"}
	vinylSideGeneratedColumns      = []string{}
)

type (
	// VinylSideSlice is an alias for a slice of pointers to VinylSide.
	// This should almost always be used instead of []VinylSide.
	VinylSideSlice []*VinylSide

	vinylSideQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vinylSideType                 = reflect.TypeOf(&VinylSide{})
	vinylSideMapping              = queries.MakeStructMapping(vinylSideType)
	vinylSidePrimaryKeyMapping, _ = queries.BindMapping(vinylSideType, vinylSideMapping, vinylSidePrimaryKeyColumns)
	vinylSideInsertCacheMut       sync.RWMutex
	vinylSideInsertCache          = make(map[string]insertCache)
	vinylSideUpdateCacheMut       sync.RWMutex
	vinylSideUpdateCache          = make(map[string]updateCache)
	vinylSideUpsertCacheMut       sync.RWMutex
	vinylSideUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single vinylSide record from the query.
func (q vinylSideQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VinylSide, error) {
	o := &VinylSide{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vinyl_sides")
	}

	return o, nil
}

// All returns all VinylSide records from the query.
func (q vinylSideQuery) All(ctx context.Context, exec boil.ContextExecutor) (VinylSideSlice, error) {
	var o []*VinylSide

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VinylSide slice")
	}

	return o, nil
}

// Count returns the count of all VinylSide records in the query.
func (q vinylSideQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vinyl_sides rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vinylSideQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vinyl_sides exists")
	}

	return count > 0, nil
}

// VinylRecord pointed to by the foreign key.
func (o *VinylSide) VinylRecord(mods ...qm.QueryMod) vinylRecordQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VinylRecordID),
	}

	queryMods = append(queryMods, mods...)

	return VinylRecords(queryMods...)
}

// Tracks retrieves all the track's Tracks with an executor.
func (o *VinylSide) Tracks(mods ...qm.QueryMod) trackQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"tracks\".\"vinyl_side_id\"=?", o.ID),
	)

	return Tracks(queryMods...)
}

// LoadVinylRecord allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (vinylSideL) LoadVinylRecord(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVinylSide interface{}, mods queries.Applicator) error {
	var slice []*VinylSide
	var object *VinylSide

	if singular {
		var ok bool
		object, ok = maybeVinylSide.(*VinylSide)
		if !ok {
			object = new(VinylSide)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVinylSide)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVinylSide))
			}
		}
	} else {
		s, ok := maybeVinylSide.(*[]*VinylSide)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVinylSide)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVinylSide))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &vinylSideR{}
		}
		args[object.VinylRecordID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vinylSideR{}
			}

			args[obj.VinylRecordID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`vinyl_records`),
		qm.WhereIn(`vinyl_records.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load VinylRecord")
	}

	var resultSlice []*VinylRecord
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice VinylRecord")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for vinyl_records")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for vinyl_records")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.VinylRecord = foreign
		if foreign.R == nil {
			foreign.R = &vinylRecordR{}
		}
		foreign.R.VinylSides = append(foreign.R.VinylSides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VinylRecordID == foreign.ID {
				local.R.VinylRecord = foreign
				if foreign.R == nil {
					foreign.R = &vinylRecordR{}
				}
				foreign.R.VinylSides = append(foreign.R.VinylSides, local)
				break
			}
		}
	}

	return nil
}

// LoadTracks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (vinylSideL) LoadTracks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVinylSide interface{}, mods queries.Applicator) error {
	var slice []*VinylSide
	var object *VinylSide

	if singular {
		var ok bool
		object, ok = maybeVinylSide.(*VinylSide)
		if !ok {
			object = new(VinylSide)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVinylSide)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVinylSide))
			}
		}
	} else {
		s, ok := maybeVinylSide.(*[]*VinylSide)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVinylSide)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVinylSide))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &vinylSideR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vinylSideR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tracks`),
		qm.WhereIn(`tracks.vinyl_side_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tracks")
	}

	var resultSlice []*Track
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tracks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tracks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tracks")
	}

	if singular {
		object.R.Tracks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &trackR{}
			}
			foreign.R.VinylSide = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.VinylSideID {
				local.R.Tracks = append(local.R.Tracks, foreign)
				if foreign.R == nil {
					foreign.R = &trackR{}
				}
				foreign.R.VinylSide = local
				break
			}
		}
	}

	return nil
}

// SetVinylRecord of the vinylSide to the related item.
// Sets o.R.VinylRecord to related.
// Adds o to related.R.VinylSides.
func (o *VinylSide) SetVinylRecord(ctx context.Context, exec boil.ContextExecutor, insert bool, related *VinylRecord) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"vinyl_sides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"vinyl_record_id"}),
		strmangle.WhereClause("\"", "\"", 2, vinylSidePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VinylRecordID = related.ID
	if o.R == nil {
		o.R = &vinylSideR{
			VinylRecord: related,
		}
	} else {
		o.R.VinylRecord = related
	}

	if related.R == nil {
		related.R = &vinylRecordR{
			VinylSides: VinylSideSlice{o},
		}
	} else {
		related.R.VinylSides = append(related.R.VinylSides, o)
	}

	return nil
}

// AddTracks adds the given related objects to the existing relationships
// of the vinyl_side, optionally inserting them as new records.
// Appends related to o.R.Tracks.
// Sets related.R.VinylSide appropriately.
func (o *VinylSide) AddTracks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Track) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.VinylSideID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"tracks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"vinyl_side_id"}),
				strmangle.WhereClause("\"", "\"", 2, trackPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.VinylSideID = o.ID
		}
	}

	if o.R == nil {
		o.R = &vinylSideR{
			Tracks: related,
		}
	} else {
		o.R.Tracks = append(o.R.Tracks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &trackR{
				VinylSide: o,
			}
		} else {
			rel.R.VinylSide = o
		}
	}
	return nil
}

// VinylSides retrieves all the records using an executor.
func VinylSides(mods ...qm.QueryMod) vinylSideQuery {
	mods = append(mods, qm.From("\"vinyl_sides\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vinyl_sides\".*"})
	}

	return vinylSideQuery{q}
}

// FindVinylSide retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVinylSide(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*VinylSide, error) {
	vinylSideObj := &VinylSide{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vinyl_sides\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, vinylSideObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vinyl_sides")
	}

	return vinylSideObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VinylSide) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vinyl_sides provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(vinylSideColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vinylSideInsertCacheMut.RLock()
	cache, cached := vinylSideInsertCache[key]
	vinylSideInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vinylSideAllColumns,
			vinylSideColumnsWithDefault,
			vinylSideColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vinylSideType, vinylSideMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vinylSideType, vinylSideMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vinyl_sides\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vinyl_sides\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vinyl_sides")
	}

	if !cached {
		vinylSideInsertCacheMut.Lock()
		vinylSideInsertCache[key] = cache
		vinylSideInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the VinylSide.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VinylSide) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	vinylSideUpdateCacheMut.RLock()
	cache, cached := vinylSideUpdateCache[key]
	vinylSideUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vinylSideAllColumns,
			vinylSidePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vinyl_sides, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vinyl_sides\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vinylSidePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vinylSideType, vinylSideMapping, append(wl, vinylSidePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vinyl_sides row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vinyl_sides")
	}

	if !cached {
		vinylSideUpdateCacheMut.Lock()
		vinylSideUpdateCache[key] = cache
		vinylSideUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q vinylSideQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vinyl_sides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vinyl_sides")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VinylSideSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylSidePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vinyl_sides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vinylSidePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vinylSide slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vinylSide")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VinylSide) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vinyl_sides provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(vinylSideColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vinylSideUpsertCacheMut.RLock()
	cache, cached := vinylSideUpsertCache[key]
	vinylSideUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vinylSideAllColumns,
			vinylSideColumnsWithDefault,
			vinylSideColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vinylSideAllColumns,
			vinylSidePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vinyl_sides, could not build update column list")
		}

		ret := strmangle.SetComplement(vinylSideAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vinylSidePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vinyl_sides, could not build conflict column list")
			}

			conflict = make([]string, len(vinylSidePrimaryKeyColumns))
			copy(conflict, vinylSidePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vinyl_sides\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vinylSideType, vinylSideMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vinylSideType, vinylSideMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vinyl_sides")
	}

	if !cached {
		vinylSideUpsertCacheMut.Lock()
		vinylSideUpsertCache[key] = cache
		vinylSideUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single VinylSide record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VinylSide) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VinylSide provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vinylSidePrimaryKeyMapping)
	sql := "DELETE FROM \"vinyl_sides\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vinyl_sides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vinyl_sides")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vinylSideQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vinylSideQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vinyl_sides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vinyl_sides")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VinylSideSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylSidePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vinyl_sides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinylSidePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vinylSide slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vinyl_sides")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VinylSide) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVinylSide(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VinylSideSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VinylSideSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinylSidePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vinyl_sides\".* FROM \"vinyl_sides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinylSidePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VinylSideSlice")
	}

	*o = slice

	return nil
}

// VinylSideExists checks if the VinylSide row exists.
func VinylSideExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vinyl_sides\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vinyl_sides exists")
	}

	return exists, nil
}

// Exists checks if the VinylSide row exists.
func (o *VinylSide) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VinylSideExists(ctx, exec, o.ID)
}
