// Code generated by go-swagger; DO NOT EDIT.

package vinyl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRecentPlaysRouteParams creates a new GetRecentPlaysRouteParams object
// with the default values initialized.
func NewGetRecentPlaysRouteParams() GetRecentPlaysRouteParams {

	var (
		// initialize parameters with default values

		limitDefault = int64(10)
	)

	return GetRecentPlaysRouteParams{
		Limit: &limitDefault,
	}
}

// GetRecentPlaysRouteParams contains all the bound params for the get recent plays route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetRecentPlaysRoute
type GetRecentPlaysRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Max number of plays to return
	  In: query
	  Default: 10
	*/
	Limit *int64 `query:"limit"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRecentPlaysRouteParams() beforehand.
func (o *GetRecentPlaysRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRecentPlaysRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// limit
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetRecentPlaysRouteParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetRecentPlaysRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	return nil
}
