// Code generated by go-swagger; DO NOT EDIT.

package vinyl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetVinylSearchRouteParams creates a new GetVinylSearchRouteParams object
// no default values defined in spec.
func NewGetVinylSearchRouteParams() GetVinylSearchRouteParams {

	return GetVinylSearchRouteParams{}
}

// GetVinylSearchRouteParams contains all the bound params for the get vinyl search route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetVinylSearchRoute
type GetVinylSearchRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Search query (artist, title, barcode)
	  Required: true
	  In: query
	*/
	Q string `query:"q"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetVinylSearchRouteParams() beforehand.
func (o *GetVinylSearchRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qQ, qhkQ, _ := qs.GetOK("q")
	if err := o.bindQ(qQ, qhkQ, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetVinylSearchRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// q
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("q", "query", o.Q); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindQ binds and validates parameter Q from query.
func (o *GetVinylSearchRouteParams) bindQ(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("q", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("q", "query", raw); err != nil {
		return err
	}

	o.Q = raw

	return nil
}
