// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/farkmi/spinsnitch-server/internal/recognizer/models"
)

// RecognizeSongRecognizePostReader is a Reader for the RecognizeSongRecognizePost structure.
type RecognizeSongRecognizePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RecognizeSongRecognizePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRecognizeSongRecognizePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewRecognizeSongRecognizePostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRecognizeSongRecognizePostOK creates a RecognizeSongRecognizePostOK with default headers values
func NewRecognizeSongRecognizePostOK() *RecognizeSongRecognizePostOK {
	return &RecognizeSongRecognizePostOK{}
}

/*
	RecognizeSongRecognizePostOK describes a response with status code 200, with default header values.

Successful Response
*/
type RecognizeSongRecognizePostOK struct {
	Payload *models.RecognitionResponse
}

func (o *RecognizeSongRecognizePostOK) Error() string {
	return fmt.Sprintf("[POST /recognize][%d] recognizeSongRecognizePostOK  %+v", 200, o.Payload)
}
func (o *RecognizeSongRecognizePostOK) GetPayload() *models.RecognitionResponse {
	return o.Payload
}

func (o *RecognizeSongRecognizePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RecognitionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRecognizeSongRecognizePostUnprocessableEntity creates a RecognizeSongRecognizePostUnprocessableEntity with default headers values
func NewRecognizeSongRecognizePostUnprocessableEntity() *RecognizeSongRecognizePostUnprocessableEntity {
	return &RecognizeSongRecognizePostUnprocessableEntity{}
}

/*
	RecognizeSongRecognizePostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type RecognizeSongRecognizePostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

func (o *RecognizeSongRecognizePostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /recognize][%d] recognizeSongRecognizePostUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *RecognizeSongRecognizePostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *RecognizeSongRecognizePostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
