// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecognitionResponse recognition response
//
// swagger:model RecognitionResponse
type RecognitionResponse struct {

	// status
	Status string `json:"status,omitempty"`

	// track
	Track *TrackInfo `json:"track,omitempty"`
}

// Validate validates this recognition response
func (m *RecognitionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTrack(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecognitionResponse) validateTrack(formats strfmt.Registry) error {
	if swag.IsZero(m.Track) { // not required
		return nil
	}

	if m.Track != nil {
		if err := m.Track.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("track")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("track")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this recognition response based on the context it is used
func (m *RecognitionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTrack(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecognitionResponse) contextValidateTrack(ctx context.Context, formats strfmt.Registry) error {

	if m.Track != nil {
		if err := m.Track.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("track")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("track")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecognitionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecognitionResponse) UnmarshalBinary(b []byte) error {
	var res RecognitionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
