// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TrackInfo track info
//
// swagger:model TrackInfo
type TrackInfo struct {

	// cover art
	CoverArt string `json:"cover_art,omitempty"`

	// shazam url
	ShazamURL string `json:"shazam_url,omitempty"`

	// subtitle
	Subtitle string `json:"subtitle,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this track info
func (m *TrackInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this track info based on context it is used
func (m *TrackInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrackInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrackInfo) UnmarshalBinary(b []byte) error {
	var res TrackInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
