// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BodyRecognizeSongRecognizePost Body_recognize_song_recognize_post
//
// swagger:model Body_recognize_song_recognize_post
type BodyRecognizeSongRecognizePost struct {

	// File
	// Required: true
	// Format: binary
	File io.ReadCloser `json:"file"`
}

// Validate validates this body recognize song recognize post
func (m *BodyRecognizeSongRecognizePost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BodyRecognizeSongRecognizePost) validateFile(formats strfmt.Registry) error {

	if err := validate.Required("file", "body", io.ReadCloser(m.File)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this body recognize song recognize post based on context it is used
func (m *BodyRecognizeSongRecognizePost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BodyRecognizeSongRecognizePost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BodyRecognizeSongRecognizePost) UnmarshalBinary(b []byte) error {
	var res BodyRecognizeSongRecognizePost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
