// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecentPlaysResponse recent plays response
//
// swagger:model recentPlaysResponse
type RecentPlaysResponse struct {

	// plays
	Plays []*TrackPlay `json:"plays"`
}

// Validate validates this recent plays response
func (m *RecentPlaysResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlays(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecentPlaysResponse) validatePlays(formats strfmt.Registry) error {
	if swag.IsZero(m.Plays) { // not required
		return nil
	}

	for i := 0; i < len(m.Plays); i++ {
		if swag.IsZero(m.Plays[i]) { // not required
			continue
		}

		if m.Plays[i] != nil {
			if err := m.Plays[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("plays" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("plays" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this recent plays response based on the context it is used
func (m *RecentPlaysResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlays(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecentPlaysResponse) contextValidatePlays(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Plays); i++ {

		if m.Plays[i] != nil {
			if err := m.Plays[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("plays" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("plays" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecentPlaysResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecentPlaysResponse) UnmarshalBinary(b []byte) error {
	var res RecentPlaysResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
